package src;

import src.about;
import src.login;
import src.Visitors;
import src.stuff;
import java.sql.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Dashboard() {
        initComponents();
        java.util.Date date = new java.util.Date();
        nn.setText(date.toString());
        filldashboard();
    }

    public void filldashboard() {
        int countv = 0;
        int counts = 0;
        int counti = 0;
        int totalmoney=0;
        String hello="";
        try {

            Connection conn = DBconnection.connectDB();
            PreparedStatement st = (PreparedStatement) conn.prepareStatement("SELECT * FROM visitors ");
            PreparedStatement st2 = (PreparedStatement) conn.prepareStatement("SELECT * FROM stuffs");

            PreparedStatement statement = (PreparedStatement) conn.prepareStatement("SELECT username FROM login");

            ResultSet x = statement.executeQuery();
            PreparedStatement st3 = (PreparedStatement) conn.prepareStatement("SELECT * FROM items");

            ResultSet rs = st.executeQuery();
            ResultSet rs2 = st2.executeQuery();
            ResultSet rs3 = st3.executeQuery();
            ResultSet rs4=statement.executeQuery();

            for (int i = 0; i < 10; i++) {
                if (rs.next()) {
                    countv++;
                }
                if (rs2.next()) {
                    counts++;
                }
                if (rs3.next()) {
                    counti++;
                }
                 if (rs4.next()) {
                    hello=rs4.getString(1);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        totalmoney=countv*5; 
        vno.setText(String.valueOf(countv));
        ino.setText(String.valueOf(counti));
        sno.setText(String.valueOf(counts));
        mno.setText(String.valueOf(totalmoney) + " ETB");
        hellolabel.setText("Welcome, Mr. "+hello);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        lprofile = new javax.swing.JLabel();
        tfabout = new javax.swing.JLabel();
        tfservices = new javax.swing.JLabel();
        tflogout = new javax.swing.JLabel();
        llogin = new javax.swing.JLabel();
        tflogout2 = new javax.swing.JLabel();
        lregister = new javax.swing.JLabel();
        bpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        vno = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hellolabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        ino = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        sno = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        mno = new javax.swing.JLabel();
        imageatback = new javax.swing.JLabel();

        jMenu2.setText("jMenu2");

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lprofile.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        lprofile.setForeground(new java.awt.Color(255, 255, 255));
        lprofile.setText("PROFILE");
        lprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lprofileMouseClicked(evt);
            }
        });
        jPanel2.add(lprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        tfabout.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        tfabout.setForeground(new java.awt.Color(255, 255, 255));
        tfabout.setText("ABOUT");
        tfabout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfabout.setFocusTraversalPolicyProvider(true);
        tfabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfaboutMouseClicked(evt);
            }
        });
        jPanel2.add(tfabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 8, 41, -1));

        tfservices.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        tfservices.setForeground(new java.awt.Color(255, 255, 255));
        tfservices.setText("SERVICES");
        tfservices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfservices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfservicesMouseClicked(evt);
            }
        });
        jPanel2.add(tfservices, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 8, -1, -1));

        tflogout.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        tflogout.setForeground(new java.awt.Color(255, 255, 255));
        tflogout.setText("LOGOUT");
        tflogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tflogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tflogoutMouseClicked(evt);
            }
        });
        jPanel2.add(tflogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 8, -1, -1));

        llogin.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        llogin.setForeground(new java.awt.Color(255, 255, 255));
        llogin.setText("Login ");
        llogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lloginMouseClicked(evt);
            }
        });
        jPanel2.add(llogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 19, -1, -1));

        tflogout2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tflogout2.setForeground(new java.awt.Color(255, 255, 255));
        tflogout2.setText("| ");
        tflogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tflogout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tflogout2MouseClicked(evt);
            }
        });
        jPanel2.add(tflogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 19, -1, -1));

        lregister.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lregister.setForeground(new java.awt.Color(255, 255, 255));
        lregister.setText("Register");
        lregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lregisterMouseClicked(evt);
            }
        });
        jPanel2.add(lregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 19, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 40));

        bpanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TMT Web Design, Copyright @ 2023");

        javax.swing.GroupLayout bpanelLayout = new javax.swing.GroupLayout(bpanel);
        bpanel.setLayout(bpanelLayout);
        bpanelLayout.setHorizontalGroup(
            bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bpanelLayout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(290, 290, 290))
        );
        bpanelLayout.setVerticalGroup(
            bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bpanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        getContentPane().add(bpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 395, 770, 30));

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Management System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 27)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Museum");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 2, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("If you wants to increase your success rate, double your failure rate.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MANAGE :");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Visitors");

        vno.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        vno.setForeground(new java.awt.Color(255, 255, 255));
        vno.setText("35");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(vno)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vno)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 130, 80));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("->  STUFF MEMBERS");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        nn.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        nn.setForeground(new java.awt.Color(255, 255, 255));
        nn.setText("Welcome, MR . Tekle");
        getContentPane().add(nn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("->  ITEMS");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 80, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-> VISITORS");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 90, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NEW USER LABEL.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 50));

        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 210, 80));

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PROFESSIONAL SYSTEM DESIGN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 20));

        hellolabel.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        hellolabel.setForeground(new java.awt.Color(255, 255, 255));
        hellolabel.setText("Welcome, MR . Tekle");
        getContentPane().add(hellolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Items");

        ino.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        ino.setForeground(new java.awt.Color(255, 255, 255));
        ino.setText("35");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(15, 15, 15))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(ino)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(ino)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total employee");

        sno.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        sno.setForeground(new java.awt.Color(255, 255, 255));
        sno.setText("35");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(sno)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sno)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 130, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total Income");

        mno.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mno.setForeground(new java.awt.Color(255, 255, 255));
        mno.setText("35");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(mno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mno)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        imageatback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inverted.jpg"))); // NOI18N
        getContentPane().add(imageatback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lprofileMouseClicked
        profile b = new profile();
        dispose();
        b.setTitle("profile");
        b.setLocationRelativeTo(null);
        b.setVisible(true);

    }//GEN-LAST:event_lprofileMouseClicked

    private void tfaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfaboutMouseClicked
        about b = new about();
        dispose();
        b.setTitle("About");
        b.setLocationRelativeTo(null);
        b.setVisible(true);

    }//GEN-LAST:event_tfaboutMouseClicked

    private void tfservicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfservicesMouseClicked
        dispose();
        services b = new services();
        b.setTitle("Services");
        b.setLocationRelativeTo(null);
        b.setVisible(true);

    }//GEN-LAST:event_tfservicesMouseClicked

    private void tflogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tflogoutMouseClicked
        try {
            Connection conn = DBconnection.connectDB();
            PreparedStatement statement = (PreparedStatement) conn.prepareStatement("delete from login");
            int x = statement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        login n = new login();
        n.setTitle("user login");
        n.setLocationRelativeTo(null);
        n.setVisible(true);
    }//GEN-LAST:event_tflogoutMouseClicked

    private void lloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lloginMouseClicked
        login b = new login();
        dispose();
        b.setTitle("login");
        b.setLocationRelativeTo(null);
        b.setVisible(true);

    }//GEN-LAST:event_lloginMouseClicked

    private void tflogout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tflogout2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tflogout2MouseClicked

    private void lregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lregisterMouseClicked
        UserRegister b = new UserRegister();
        dispose();
        b.setTitle("reister");
        b.setLocationRelativeTo(null);
        b.setVisible(true);
    }//GEN-LAST:event_lregisterMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
        Visitors b = new Visitors();
        b.setTitle("manage visitors");
        b.setLocationRelativeTo(null);
        b.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();
        stuff b = new stuff();
        b.setTitle("manage stuff members");
        b.setLocationRelativeTo(null);
        b.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        dispose();
        items b = new items();
        b.setTitle("manage items");
        b.setLocationRelativeTo(null);
        b.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bpanel;
    private javax.swing.JLabel hellolabel;
    private javax.swing.JLabel imageatback;
    private javax.swing.JLabel ino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel llogin;
    private javax.swing.JLabel lprofile;
    private javax.swing.JLabel lregister;
    private javax.swing.JLabel mno;
    private javax.swing.JLabel nn;
    private javax.swing.JLabel sno;
    private javax.swing.JLabel tfabout;
    private javax.swing.JLabel tflogout;
    private javax.swing.JLabel tflogout2;
    private javax.swing.JLabel tfservices;
    private javax.swing.JLabel vno;
    // End of variables declaration//GEN-END:variables
}
