/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.sql.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class forget extends javax.swing.JFrame {

    /**
     * Creates new form forget
     */
    public forget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        passerror = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfpass1 = new javax.swing.JTextField();
        tfpass2 = new javax.swing.JTextField();
        btnpassupdate = new javax.swing.JButton();
        btnpasscancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfnext = new javax.swing.JTextField();
        btnnext = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        dialog1.setModal(true);
        dialog1.setSize(new java.awt.Dimension(350, 250));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passerror.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passerror.setForeground(new java.awt.Color(255, 0, 0));
        passerror.setText("  ");
        jPanel2.add(passerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm password:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 102, 108, -1));

        tfpass1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(tfpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 58, 137, -1));

        tfpass2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(tfpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 96, 137, -1));

        btnpassupdate.setBackground(new java.awt.Color(51, 102, 255));
        btnpassupdate.setText("UPDATE");
        btnpassupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpassupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnpassupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, -1));

        btnpasscancel.setBackground(new java.awt.Color(51, 102, 255));
        btnpasscancel.setText("CANCEL");
        btnpasscancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpasscancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnpasscancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 140, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("YOUR ID : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 37, -1, -1));

        idlabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idlabel.setForeground(new java.awt.Color(255, 255, 255));
        idlabel.setText("YOUR ID : ");
        jPanel2.add(idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 37, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter new password: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 64, -1, -1));

        javax.swing.GroupLayout dialog1Layout = new javax.swing.GroupLayout(dialog1.getContentPane());
        dialog1.getContentPane().setLayout(dialog1Layout);
        dialog1Layout.setHorizontalGroup(
            dialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
        dialog1Layout.setVerticalGroup(
            dialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Find your account");

        tfnext.setBackground(new java.awt.Color(102, 102, 102));
        tfnext.setForeground(new java.awt.Color(204, 204, 204));
        tfnext.setText("username,email address or phone #");
        tfnext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        tfnext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfnextMouseClicked(evt);
            }
        });
        tfnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnextActionPerformed(evt);
            }
        });

        btnnext.setBackground(new java.awt.Color(51, 153, 255));
        btnnext.setForeground(new java.awt.Color(255, 255, 255));
        btnnext.setText("Next");
        btnnext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Enter your username or the email address  ");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("or phone number linked to your account.");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<~");
        jLabel2.setToolTipText("Back");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(tfnext, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(tfnext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnext)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfnextMouseClicked
        tfnext.setText("");
        btnnext.setBackground(Color.BLUE);
    }//GEN-LAST:event_tfnextMouseClicked

    private void tfnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnextActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        String key = tfnext.getText();
        Connection conn = DBconnection.connectDB();
        try {
            PreparedStatement st = (PreparedStatement) conn.prepareStatement("SELECT users.id,question_no,value FROM users JOIN backup ON users.id=backup.user_id WHERE username=? OR email=? OR phone=?");
            st.setString(1, key);
            st.setString(2, key);
            st.setString(3, key);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                int index = Integer.parseInt(rs.getString(2));
                String user_id = rs.getString(1);
                String value = rs.getString(3);
                if (index == 0) {
                    String m = JOptionPane.showInputDialog(this, "What is your birth place?", "security question", JOptionPane.QUESTION_MESSAGE);
                    if (m.equalsIgnoreCase(value)) {
                        dispose();
                        idlabel.setText(user_id);
                        dialog1.setLocationRelativeTo(null);
                        dialog1.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "incorrect answer.");
                    }

                } else if (index == 1) {
                    String m = JOptionPane.showInputDialog(this, "What is your favourite color?", "security question", JOptionPane.QUESTION_MESSAGE);
                    if (m.equalsIgnoreCase(value)) {
                        dispose();
                        idlabel.setText(user_id);
                        dialog1.setLocationRelativeTo(null);
                        dialog1.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "incorrect answer.");
                    }
                } else if (index == 2) {
                    String m = JOptionPane.showInputDialog(this, "What is your favourite food?", "security question", JOptionPane.QUESTION_MESSAGE);
                    if (m.equalsIgnoreCase(value)) {
                        dispose();
                        idlabel.setText(user_id);
                        dialog1.setLocationRelativeTo(null);
                        dialog1.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "incorrect answer.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "NOT FOUND!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(forget.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        login b = new login();
        dispose();
        b.setTitle("Login.");
        b.setLocationRelativeTo(null);
        b.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnpassupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpassupdateActionPerformed
        String p = idlabel.getText();
        String p1 = tfpass1.getText();
        String p2 = tfpass2.getText();
        if (p1.equals(p2)) {
            try {
                Connection connect = DBconnection.connectDB();
                PreparedStatement st = (PreparedStatement) connect.prepareStatement("UPDATE users SET password=? WHERE id=?");
                st.setString(1, p1);
                st.setString(2, p);
                int x = st.executeUpdate();
                connect.close();
                
                dialog1.setVisible(false);
                JOptionPane.showMessageDialog(this, "Your password is Updated.");
                login t = new login();
                dispose();
                t.setTitle("login");
                t.setLocationRelativeTo(null);
                t.setVisible(true);

                connect.close();
            } catch (SQLException ex) {
                Logger.getLogger(forget.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            passerror.setText("password mismatch !!");
        }
    }//GEN-LAST:event_btnpassupdateActionPerformed

    private void btnpasscancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpasscancelActionPerformed
        dialog1.setVisible(false);
                login t = new login();
//                dispose();
                t.setTitle("login");
                t.setLocationRelativeTo(null);
                t.setVisible(true);
    }//GEN-LAST:event_btnpasscancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnpasscancel;
    private javax.swing.JButton btnpassupdate;
    private javax.swing.JDialog dialog1;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passerror;
    private javax.swing.JTextField tfnext;
    private javax.swing.JTextField tfpass1;
    private javax.swing.JTextField tfpass2;
    // End of variables declaration//GEN-END:variables

    private void update_password(String id_value) {

        try {
            Connection connect = DBconnection.connectDB();
            PreparedStatement st = (PreparedStatement) connect.prepareStatement("UPDATE users SET password=? WHERE=?");
        } catch (SQLException ex) {
            Logger.getLogger(forget.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
