package src;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class items extends javax.swing.JFrame {

    public items() {
        initComponents();
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        iname1 = new javax.swing.JTextField();
        idate1 = new javax.swing.JTextField();
        btnupdate1 = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        iscroll1 = new javax.swing.JScrollPane();
        ides1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        iid1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        image_viwer = new javax.swing.JDialog();
        image_label = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        tfsearch = new javax.swing.JTextField();
        tfhome = new javax.swing.JLabel();
        cbsearch = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        iname = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        idate = new javax.swing.JTextField();
        iid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        iscroll = new javax.swing.JScrollPane();
        ides = new javax.swing.JTextArea();
        btnimg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsum = new javax.swing.JTextArea();
        imagelabel = new javax.swing.JLabel();
        btnprint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        updialog.setTitle("update");
        updialog.setModal(true);
        updialog.setSize(new java.awt.Dimension(490, 280));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Item Name   ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Reg. Date");

        iname1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        idate1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnupdate1.setText("Update");
        btnupdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });

        btnclose.setText("CLOSE");
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Item Describtion :   ");

        iscroll1.setBackground(new java.awt.Color(255, 255, 255));
        iscroll1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iscroll1.setForeground(new java.awt.Color(153, 153, 153));

        ides1.setColumns(20);
        ides1.setRows(5);
        ides1.setToolTipText("item describtion");
        iscroll1.setViewportView(ides1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idate1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(iname1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(iscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnupdate1)
                            .addComponent(btnclose))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(idate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnupdate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclose))
                    .addComponent(iscroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(48, 48, 48))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update Stuff's info");

        iid1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("ID :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iid1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updialogLayout = new javax.swing.GroupLayout(updialog.getContentPane());
        updialog.getContentPane().setLayout(updialogLayout);
        updialogLayout.setHorizontalGroup(
            updialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updialogLayout.setVerticalGroup(
            updialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updialogLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        image_viwer.setModal(true);
        image_viwer.setSize(new java.awt.Dimension(420, 320));
        image_viwer.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image_labelMouseClicked(evt);
            }
        });
        image_viwer.getContentPane().add(image_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 290));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(0, 0, 51));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("MANAGE ITEM");

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/icons8_search_20px.png"))); // NOI18N
        search.setText(" ");
        search.setToolTipText("search...");
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });

        tfsearch.setForeground(new java.awt.Color(51, 51, 51));

        tfhome.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        tfhome.setForeground(new java.awt.Color(255, 255, 255));
        tfhome.setText("HOME");
        tfhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfhome.setFocusTraversalPolicyProvider(true);
        tfhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfhomeMouseClicked(evt);
            }
        });

        cbsearch.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        cbsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "search by :", "ID", "Name" }));
        cbsearch.setToolTipText("choose the key to searc");
        cbsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfhome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search)
                .addGap(14, 14, 14))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search)
                        .addComponent(tfhome)
                        .addComponent(cbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Item ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 56, 60, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("IMAGE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 6, -1, 20));

        btnclear.setBackground(new java.awt.Color(204, 204, 204));
        btnclear.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.setActionCommand("");
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 198, -1, -1));

        iname.setBackground(new java.awt.Color(255, 204, 204));
        iname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(iname, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 36, 160, 20));

        btnupdate.setBackground(new java.awt.Color(204, 204, 204));
        btnupdate.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.setActionCommand("");
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 198, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Item Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, 60, 20));

        btnadd.setBackground(new java.awt.Color(204, 204, 204));
        btnadd.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btnadd.setText("ADD");
        btnadd.setActionCommand("");
        btnadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 198, -1, -1));

        idate.setBackground(new java.awt.Color(255, 204, 204));
        idate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        idate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idateMouseClicked(evt);
            }
        });
        jPanel1.add(idate, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 166, 133, 20));

        iid.setBackground(new java.awt.Color(255, 204, 204));
        iid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(iid, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 76, 160, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date of register.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 139, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Item Describtion");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 96, 98, 20));

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.setActionCommand("");
        btndelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 198, -1, -1));

        iscroll.setBackground(new java.awt.Color(255, 255, 255));
        iscroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iscroll.setForeground(new java.awt.Color(153, 153, 153));

        ides.setColumns(20);
        ides.setRows(5);
        ides.setToolTipText("item describtion");
        iscroll.setViewportView(ides);

        jPanel1.add(iscroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 122, 160, 64));

        btnimg.setBackground(new java.awt.Color(204, 204, 204));
        btnimg.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btnimg.setText("Brows Image");
        btnimg.setActionCommand("");
        btnimg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnimg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnimgMouseClicked(evt);
            }
        });
        jPanel1.add(btnimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 109, -1, -1));

        itemsum.setEditable(false);
        itemsum.setColumns(20);
        itemsum.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        itemsum.setRows(5);
        itemsum.setToolTipText("Item summery");
        itemsum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(itemsum);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 6, 367, 176));

        imagelabel.setBackground(new java.awt.Color(157, 96, 102));
        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/icons8_administrator_male_50px.png"))); // NOI18N
        imagelabel.setToolTipText("Expand image");
        imagelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        imagelabel.setCursor(new java.awt.Cursor(java.awt.Cursor.NE_RESIZE_CURSOR));
        imagelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagelabelMouseClicked(evt);
            }
        });
        jPanel1.add(imagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 32, 180, 71));

        btnprint.setBackground(new java.awt.Color(204, 204, 204));
        btnprint.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btnprint.setText("PRINT");
        btnprint.setActionCommand("");
        btnprint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprintMouseClicked(evt);
            }
        });
        jPanel1.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 198, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item List");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 228, 747, -1));

        table1.setAutoCreateRowSorter(true);
        table1.setBackground(new java.awt.Color(204, 204, 204));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Item Describtion", "Date Of Register."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setToolTipText("list of items");
        table1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setResizable(false);
            table1.getColumnModel().getColumn(1).setResizable(false);
            table1.getColumnModel().getColumn(2).setResizable(false);
            table1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 257, 747, 85));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visimg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        int id = 0;
        String name = "";
        String desc = "";
        String date = "";

        try {
            String key = tfsearch.getText();
            Connection conn = (Connection) DBconnection.connectDB();
            PreparedStatement st = (PreparedStatement) conn.prepareStatement(
                    "SELECT * FROM items WHERE id=? or item_name=? or item_desc=? or date=?");
            st.setString(1, key);
            st.setString(2, key);
            st.setString(3, key);
            st.setString(4, key);

            ResultSet rs = st.executeQuery();
            clearTable();
            for (int i = 0; i < 10; i++) {
                if (rs.next()) {
                    id = rs.getInt(1);
                    name = rs.getString(2);
                    desc = rs.getString(3);
                    date = rs.getString(4);

                    table1.setValueAt(id, i, 0);
                    table1.setValueAt(name, i, 1);
                    table1.setValueAt(desc, i, 2);
                    table1.setValueAt(date, i, 3);

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_searchMouseClicked


    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed

        itemsum.setText("");
        iname.setText("");
        iid.setText("");
        ides.setText("");
        idate.setText("");
        int y = table1.getSelectedRow();
        if (table1.isRowSelected(y)) {
            table1.removeRowSelectionInterval(y, 0);
        }


    }//GEN-LAST:event_btnclearActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int key = table1.getSelectedRow();

        if (table1.isRowSelected(key)) {

            iid1.setText(table1.getValueAt(key, 0).toString());
            iname1.setText(table1.getValueAt(key, 1).toString());
            ides1.setText(table1.getValueAt(key, 2).toString());
            idate1.setText(table1.getValueAt(key, 3).toString());
            updialog.setLocationRelativeTo(null);
            updialog.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "select row to be updated first.", "select!!", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

        if (iname.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "name of item is empty!", "error.", JOptionPane.ERROR_MESSAGE);

        } else if (iid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter item id!", "error.", JOptionPane.ERROR_MESSAGE);
        } else if (ides.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter item's describtion!", "error.", JOptionPane.ERROR_MESSAGE);

        } else if (idate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter reg. date!", "error.", JOptionPane.ERROR_MESSAGE);

        } else {
            String name = iname.getText();
            String id = iid.getText();
            String desc = ides.getText();
            String date = idate.getText();
            itemsTable(id, name, desc, date);  //to insert the value to database

        }


    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        String y = JOptionPane.showInputDialog(this, "ID of Stuff member to be deleted.", "Enter ID", JOptionPane.INFORMATION_MESSAGE);
        if (!y.isEmpty()) {
            deleteItem(y);
        } else {
            System.out.println("delete canceled");
        }

    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnimgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnimgMouseClicked

        // iimage.setText("image is not avaliable!");
        JFileChooser t = new JFileChooser();
        t.showOpenDialog(jPanel1);

        String key = t.getSelectedFile().getName().toString();
        ImageIcon i1=new ImageIcon(ClassLoader.getSystemResource("icons/"+key));
        imagelabel.setIcon(i1);
        

    }//GEN-LAST:event_btnimgMouseClicked

    private void btnprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseClicked
        if (itemsum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "there is nothing to print!", "error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                java.util.Date date = new java.util.Date();
                itemsum.setText(itemsum.getText() + "\n" + "****************************************************");
                itemsum.setText(itemsum.getText() + "\nGenerated on : " + date.toString());
                itemsum.print();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnprintMouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        int key = table1.getSelectedRow();
        itemsum.setBackground(Color.LIGHT_GRAY);
        itemsum.setText("                           ...::::::::::MMS::::::::::...\n"
                + "\n"
                + "ITEM SUMMARY:\n"
                + "****************************************************");
        itemsum.setText(itemsum.getText() + "\n" + "\n" + "ITEM NAME     : " + table1.getValueAt(key, 1) + "\n" + "ITEM ID            :  " + table1.getValueAt(key, 0) + "\n" + "DESCRIPTION : " + table1.getValueAt(key, 2)
                + "\n" + "DATE OF REG. : " + table1.getValueAt(key, 3));

    }//GEN-LAST:event_table1MouseClicked

    private void idateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idateMouseClicked
        idate.setText("");
    }//GEN-LAST:event_idateMouseClicked

    private void tfhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfhomeMouseClicked
        Dashboard b = new Dashboard();
        dispose();
        b.setTitle("HOME");
        b.setLocationRelativeTo(null);
        b.setVisible(true);
    }//GEN-LAST:event_tfhomeMouseClicked

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        int key = table1.getSelectedRow();
        String preId = table1.getValueAt(key, 0).toString();
        int id = Integer.parseInt(iid1.getText());
        String name = iname1.getText();
        String date = idate1.getText();
        String desc = ides1.getText();

        updateItems(preId, id, name, desc, date);
        clearTable();
        displayTable();
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        updialog.setVisible(false);
    }//GEN-LAST:event_btncloseActionPerformed

    private void imagelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagelabelMouseClicked
//        JFileChooser t = new JFileChooser();
//        String key = t.getSelectedFile().getName().toString();
//        ImageIcon icon=new ImageIcon(ClassLoader.getSystemResource("icons/"+key));
        imagelabel.getIcon();
        image_label.setIcon(imagelabel.getIcon());
        image_viwer.setTitle("Item Image.");
        image_viwer.setLocationRelativeTo(null);
        image_viwer.setVisible(true);
    }//GEN-LAST:event_imagelabelMouseClicked

    private void image_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_labelMouseClicked
        image_viwer.setVisible(false);
    }//GEN-LAST:event_image_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnimg;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JComboBox<String> cbsearch;
    private javax.swing.JTextField idate;
    private javax.swing.JTextField idate1;
    private javax.swing.JTextArea ides;
    private javax.swing.JTextArea ides1;
    private javax.swing.JTextField iid;
    private javax.swing.JTextField iid1;
    private javax.swing.JLabel image_label;
    private javax.swing.JDialog image_viwer;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JTextField iname;
    private javax.swing.JTextField iname1;
    private javax.swing.JScrollPane iscroll;
    private javax.swing.JScrollPane iscroll1;
    private javax.swing.JTextArea itemsum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel search;
    private javax.swing.JTable table1;
    private javax.swing.JLabel tfhome;
    private javax.swing.JTextField tfsearch;
    private javax.swing.JDialog updialog;
    // End of variables declaration//GEN-END:variables

    private void itemsTable(String id, String name, String desc, String date) {
        try {
            Connection connect = (Connection) DBconnection.connectDB();
            PreparedStatement st = (PreparedStatement) connect.prepareStatement("INSERT INTO items VALUES (?,?,?,?)");
            st.setString(1, id);
            st.setString(2, name);
            st.setString(3, desc);
            st.setString(4, date);

            int x = st.executeUpdate();
            JOptionPane.showMessageDialog(this, "item added successfully");
            iid.setText("");
            iname.setText("");
            idate.setText("");
            ides.setText("");

            connect.close();
            displayTable();
        } catch (SQLException ex) {
            Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void displayTable() {
        int id = 0;
        String name = "";
        String desc = "";
        String date = "";

        try {
            Connection conn = (Connection) DBconnection.connectDB();
            PreparedStatement add = (PreparedStatement) conn.prepareStatement("SELECT * FROM items");
            ResultSet rs = add.executeQuery();
//            table1.setModel(DbUtils.resultSetToTableModel(rs));
            int no_row = table1.getRowCount();
            for (int i = 0; i < no_row; i++) {
                if (rs.next()) {
                    id = rs.getInt(1);
                    name = rs.getString(2);
                    desc = rs.getString(3);
                    date = rs.getString(4);

                    table1.setValueAt(id, i, 0);
                    table1.setValueAt(name, i, 1);
                    table1.setValueAt(desc, i, 2);
                    table1.setValueAt(date, i, 3);

                }
            }
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void deleteItem(String y) {
        int b = JOptionPane.showConfirmDialog(this, "confirm?", "", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            try {
                Connection conn = (Connection) DBconnection.connectDB();
                PreparedStatement delete = (PreparedStatement) conn.prepareStatement("DELETE FROM items WHERE id=?");
                delete.setInt(1, Integer.parseInt(y));
                int x = delete.executeUpdate();
                conn.close();
                clearTable();
                displayTable();
            } catch (SQLException ex) {
                Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void clearTable() {
        int no = table1.getRowCount();
        for (int i = 0; i < no; i++) {
            table1.setValueAt(null, i, 0);
            table1.setValueAt(null, i, 1);
            table1.setValueAt(null, i, 2);
            table1.setValueAt(null, i, 3);

        }
    }

    private void updateItems(String preId, int id, String name, String desc, String date) {
        try {
            Connection conn = (Connection) DBconnection.connectDB();
            PreparedStatement update = (PreparedStatement) conn.prepareStatement("UPDATE items SET id=?,item_name=?,item_desc=?,date=? WHERE id=? ");
            update.setInt(1, id);
            update.setString(2, name);
            update.setString(3, desc);
            update.setString(4, date);
            update.setString(5, preId);

            int y = update.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item is updated ");
            updialog.setVisible(false);
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
