package src;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form profile
     */
    public profile() {
        initComponents();
        printValues();
    }

    public String getId() {
        String key = "";
        try {
            Connection conn = DBconnection.connectDB();
            PreparedStatement statement = (PreparedStatement) conn.prepareStatement("SELECT * FROM login");

            ResultSet x = statement.executeQuery();
            if (x.next()) {
                key = x.getString("user_id");
            }
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return key;
    }

    private void printValues() {
//        String name="";
        try {

            String userid = getId();
            Connection connect = DBconnection.connectDB();
            PreparedStatement st = (PreparedStatement) connect.prepareStatement("SELECT * FROM users WHERE id=?");
            st.setString(1, userid);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
//                name=rs.getString(2);
                lfullname.setText(rs.getString(2) + " " + rs.getString(3));
                lid.setText(rs.getString(1));
                lage.setText(rs.getString(5));
                lgender.setText(rs.getString(4));
                laddress.setText(rs.getString(6));
                lphone.setText(rs.getString(7));
                lemail.setText(rs.getString(8));
                lusername.setText(rs.getString(9));
                lpassword.setText(rs.getString(10));
            }

            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
        }
//    lfullname.setText(name);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatepro = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tfname1 = new javax.swing.JTextField();
        tfname2 = new javax.swing.JTextField();
        tfage = new javax.swing.JTextField();
        tfadd = new javax.swing.JTextField();
        tfphone = new javax.swing.JTextField();
        tfpass = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        cbgender = new javax.swing.JComboBox<>();
        btnupdate = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        tfuser = new javax.swing.JTextField();
        image2 = new javax.swing.JLabel();
        lfullname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lphone = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lemail = new javax.swing.JLabel();
        lgender = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lage = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        laddress = new javax.swing.JLabel();
        lusername = new javax.swing.JLabel();
        lpassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lid = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        updatepro.setModal(true);
        updatepro.setSize(new java.awt.Dimension(470, 300));
        updatepro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Update Profile");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        updatepro.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 458, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("E-mail    : ");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 101, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("gender ");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 99, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel26.setText("Address ");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 128, 55, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Username  : ");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 45, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("password :");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 74, 62, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Phone");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, 47, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("First Name   ");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Last Name  ");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 45, -1, -1));

        tfname1.setBackground(new java.awt.Color(204, 255, 204));
        tfname1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(tfname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 14, 125, -1));

        tfname2.setBackground(new java.awt.Color(204, 255, 204));
        tfname2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(tfname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 43, 125, -1));

        tfage.setBackground(new java.awt.Color(204, 255, 204));
        tfage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(tfage, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 153, 126, -1));

        tfadd.setBackground(new java.awt.Color(204, 255, 204));
        tfadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaddActionPerformed(evt);
            }
        });
        jPanel5.add(tfadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 126, 126, -1));

        tfphone.setBackground(new java.awt.Color(204, 255, 204));
        tfphone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(tfphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 125, -1));

        tfpass.setBackground(new java.awt.Color(204, 255, 204));
        tfpass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(tfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 72, 147, -1));

        tfemail.setBackground(new java.awt.Color(204, 255, 204));
        tfemail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(tfemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 99, 147, -1));

        cbgender.setBackground(new java.awt.Color(204, 255, 204));
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        cbgender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(cbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 95, -1, -1));

        btnupdate.setText("Update");
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        btnclose.setText("CLOSE");
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel5.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Age ");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 155, -1, -1));

        tfuser.setBackground(new java.awt.Color(204, 255, 204));
        tfuser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuserActionPerformed(evt);
            }
        });
        jPanel5.add(tfuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 43, 147, -1));

        image2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Saved Pictures\\pexels-pixabay-531880 (2).jpg")); // NOI18N
        image2.setText("jLabel1");
        jPanel5.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 260));

        updatepro.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 458, 251));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lfullname.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lfullname.setForeground(new java.awt.Color(255, 255, 255));
        lfullname.setText(" ");
        getContentPane().add(lfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contact  NO.:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, -1));

        lphone.setForeground(new java.awt.Color(255, 255, 255));
        lphone.setText(" ");
        getContentPane().add(lphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("E-mail    : ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lemail.setForeground(new java.awt.Color(255, 255, 255));
        lemail.setText(" ");
        getContentPane().add(lemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 60, -1));

        lgender.setForeground(new java.awt.Color(255, 255, 255));
        lgender.setText(" j");
        getContentPane().add(lgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Age       : ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        lage.setForeground(new java.awt.Color(255, 255, 255));
        lage.setText(" ");
        getContentPane().add(lage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Address     : ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Username  : ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("password   :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        laddress.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(laddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, 20));

        lusername.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 160, 20));

        lpassword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Full Name : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        lid.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lid.setForeground(new java.awt.Color(255, 255, 255));
        lid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lid.setText("7");
        getContentPane().add(lid, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 40, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/EDIT.png"))); // NOI18N
        jLabel16.setText("Edit Profile");
        jLabel16.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Passenger ID : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Home");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("About");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Services");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("gender   : ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proimg.jpg"))); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        String key = getId();
        String i = "";
        String add = "";
        String name = "";
        String name2 = "";
        String phone = "";
        String email = "";
        String a = "";
        String sex = "";
        String use = "";
        String pa = "";

        try {
            Connection connect = DBconnection.connectDB();//now its connected
            PreparedStatement statement = (PreparedStatement) connect.prepareStatement("select * from users WHERE id =?");
            statement.setString(1, key);
            ResultSet result = statement.executeQuery();
            if (result.next()) {
//                i=result.getString("id");
                name = result.getString("fname");
                name2 = result.getString("lname");
                phone = result.getString("phone");
                add = result.getString("address");
                email = result.getString("email");
                a = result.getString("age");
                sex = result.getString("gender");
                use = result.getString("username");
                pa = result.getString("password");

            }
        } catch (SQLException ex) {
            Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
        }
//        if (sex.equalsIgnoreCase("male")) {
//            cbgender.setSelectedItem("male");
//        }
//        else
//        {
//            cbgender.setSelectedItem("female");
//        }
        tfadd.setText(add);
        tfname1.setText(name);
        tfname2.setText(name2);
        tfphone.setText(phone);
        tfemail.setText(email);
        tfage.setText(a);
        tfuser.setText(use);
        tfpass.setText(pa);
//        tfid.setText(i);
        updatepro.setLocationRelativeTo(this);
        updatepro.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void tfaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int h = JOptionPane.showConfirmDialog(this, "are you sure?", "confirm", JOptionPane.YES_NO_OPTION);
        if (h == JOptionPane.YES_OPTION) {
            try {
//                String uid = tfid.getText();
                String key = getId();
                String fname = tfname1.getText();
                String lname = tfname2.getText();
                int age = Integer.parseInt(tfage.getText());
                String gender = (String) cbgender.getSelectedItem();
                String add = tfadd.getText();
                String email = tfemail.getText();
                String phone = tfphone.getText();
                String username = tfuser.getText();
                String password = tfpass.getText();

                Connection conn = DBconnection.connectDB();
                PreparedStatement st = (PreparedStatement) conn.prepareStatement("UPDATE users SET fname=?,lname=?,age=?,gender=?,address=?,email=?,phone=?,username=?,password=? WHERE id=?");

//                st.setString(1, uid);
                st.setString(1, fname);
                st.setString(2, lname);
                st.setInt(3, age);
                st.setString(4, gender);
                st.setString(5, add);
                st.setString(6, email);
                st.setString(7, phone);
                st.setString(8, username);
                st.setString(9, password);
                st.setString(10, key);
                int x = st.executeUpdate();
                updatepro.setVisible(false);
                JOptionPane.showMessageDialog(this, "profile Updated!");
                printValues();

            } catch (SQLException ex) {
                Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        updatepro.setVisible(false);
    }//GEN-LAST:event_btncloseActionPerformed

    private void tfuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuserActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Dashboard d = new Dashboard();
        dispose();
        d.setTitle("homepage");
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        about d = new about();
        dispose();
        d.setTitle("homepage");
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        services d = new services();
        dispose();
        d.setTitle("homepage");
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel laddress;
    private javax.swing.JLabel lage;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lfullname;
    private javax.swing.JLabel lgender;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel lpassword;
    private javax.swing.JLabel lphone;
    private javax.swing.JLabel lusername;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfage;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfname1;
    private javax.swing.JTextField tfname2;
    private javax.swing.JTextField tfpass;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfuser;
    private javax.swing.JDialog updatepro;
    // End of variables declaration//GEN-END:variables
}
