package src;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tekleyesus munye
 */
public class stuff extends javax.swing.JFrame {

    /**
     * Creates new form stuff
     */
    public stuff() {
        initComponents();
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfname1 = new javax.swing.JTextField();
        tfname2 = new javax.swing.JTextField();
        tfage = new javax.swing.JTextField();
        tfadd = new javax.swing.JTextField();
        tfphone = new javax.swing.JTextField();
        tfdate = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        cbgender = new javax.swing.JComboBox<>();
        btnupdate1 = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfsearch = new javax.swing.JTextField();
        tfhome = new javax.swing.JLabel();
        cbsearch = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        vname1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vage = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        vemail = new javax.swing.JTextField();
        vadd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        vsex = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        vphone = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        vname2 = new javax.swing.JTextField();
        pbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stuff_sum = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        vdate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        tfid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        updialog.setTitle("update");
        updialog.setModal(true);
        updialog.setSize(new java.awt.Dimension(490, 280));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("E-mail : ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("gender ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Age ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel25.setText("Address ");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Visit Date :");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Phone");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("First Name   ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Last Name  ");

        tfname1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tfname2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tfage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tfadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaddActionPerformed(evt);
            }
        });

        tfphone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tfdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tfemail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        cbgender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnupdate1.setText("Update");
        btnupdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });

        btnclose.setText("CLOSE");
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfname1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 46, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnupdate1)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnclose))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfname2)
                            .addComponent(tfage))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel22))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdate, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(tfemail)
                            .addComponent(tfadd, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfphone)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tfname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(tfdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tfname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(cbgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnupdate1)
                            .addComponent(btnclose))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(tfphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Stuff's info");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("ID :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap())
        );

        javax.swing.GroupLayout updialogLayout = new javax.swing.GroupLayout(updialog.getContentPane());
        updialog.getContentPane().setLayout(updialogLayout);
        updialogLayout.setHorizontalGroup(
            updialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updialogLayout.setVerticalGroup(
            updialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updialogLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(0, 0, 51));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("Add Stuff Member");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 5, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/icons8_search_20px.png"))); // NOI18N
        jLabel4.setText(" ");
        jLabel4.setToolTipText("search");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        tfsearch.setForeground(new java.awt.Color(204, 204, 204));
        tfsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfsearchMouseClicked(evt);
            }
        });
        tfsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearchActionPerformed(evt);
            }
        });
        jPanel7.add(tfsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 139, -1));

        tfhome.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        tfhome.setForeground(new java.awt.Color(255, 255, 255));
        tfhome.setText("HOME");
        tfhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfhome.setFocusTraversalPolicyProvider(true);
        tfhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfhomeMouseClicked(evt);
            }
        });
        jPanel7.add(tfhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 13, 41, 20));

        cbsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "search by :", "ID", "Name", "Gender" }));
        cbsearch.setToolTipText("choose the key to searc");
        cbsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(cbsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lastname");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 43, 60, 20));

        vname1.setBackground(new java.awt.Color(255, 204, 204));
        vname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        vname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vname1KeyPressed(evt);
            }
        });
        jPanel3.add(vname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 23, 160, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Firstname");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 3, 60, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Gender");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 135, 60, 20));

        vage.setBackground(new java.awt.Color(255, 204, 204));
        vage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(vage, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 103, 160, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Age");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 83, 60, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-mail address");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 45, -1, 20));

        vemail.setBackground(new java.awt.Color(255, 204, 204));
        vemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(vemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 68, 160, 20));

        vadd.setBackground(new java.awt.Color(255, 204, 204));
        vadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(vadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 23, 160, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 3, 60, 20));

        vsex.setBackground(new java.awt.Color(0, 0, 51));
        vsex.setForeground(new java.awt.Color(255, 255, 255));
        vsex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        vsex.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vsexItemStateChanged(evt);
            }
        });
        jPanel3.add(vsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 155, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone #");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 94, -1, 20));

        vphone.setBackground(new java.awt.Color(255, 204, 204));
        vphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(vphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 119, 160, 20));

        btnadd.setBackground(new java.awt.Color(204, 204, 204));
        btnadd.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btnadd.setText("ADD");
        btnadd.setToolTipText("add member");
        btnadd.setActionCommand("");
        btnadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddMouseClicked(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel3.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 197, -1, -1));

        vname2.setBackground(new java.awt.Color(255, 204, 204));
        vname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        vname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vname2ActionPerformed(evt);
            }
        });
        jPanel3.add(vname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 63, 160, 20));

        pbutton.setBackground(new java.awt.Color(153, 153, 153));
        pbutton.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        pbutton.setText("PRINT");
        pbutton.setToolTipText("to print to pdf format");
        pbutton.setActionCommand("");
        pbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pbuttonMouseClicked(evt);
            }
        });
        pbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(pbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 196, -1, -1));

        table1.setBackground(new java.awt.Color(204, 204, 204));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FirstName", "Lastname", "Age", "GENDER", "ADDRESS", "EMAIL", "PHONE", "Reg. DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setToolTipText("select row to see stuff member");
        table1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        table1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 256, 836, 110));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stuff List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 233, 836, -1));

        stuff_sum.setEditable(false);
        stuff_sum.setColumns(20);
        stuff_sum.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        stuff_sum.setRows(5);
        stuff_sum.setToolTipText("stuff sammury");
        stuff_sum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(stuff_sum);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 14, 431, 176));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setToolTipText("clear all info from text area");
        jButton2.setActionCommand("");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 197, -1, -1));

        btnupdate.setBackground(new java.awt.Color(204, 204, 204));
        btnupdate.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.setToolTipText("to update stuff member");
        btnupdate.setActionCommand("");
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupdateMouseEntered(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 197, -1, -1));

        vdate.setBackground(new java.awt.Color(255, 204, 204));
        vdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        vdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdateActionPerformed(evt);
            }
        });
        jPanel3.add(vdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 171, 160, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date of register.");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 145, -1, 20));

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.setToolTipText("delete stuff member");
        btndelete.setActionCommand("");
        btndelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 197, -1, -1));
        jPanel3.add(tfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 155, 72, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("ID :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 135, 60, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visimg.jpg"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int id = 0;
        String fname = "";
        String lname = "";
        int age = 0;
        String gender = "";
        String address = "";
        String email = "";
        String phone = "";
        String date = "";
        try {
            String key = tfsearch.getText();
            Connection conn = (Connection) DBconnection.connectDB();
            PreparedStatement st = (PreparedStatement) conn.prepareStatement(
                    "SELECT * FROM stuffs WHERE id=? or fname=? or lname=? or age=?  or gender=? or address=? or email=? or phone =? or date=?");
            st.setString(1, key);
            st.setString(2, key);
            st.setString(3, key);
            st.setString(4, key);
            st.setString(5, key);
            st.setString(6, key);
            st.setString(7, key);
            st.setString(8, key);
            st.setString(9, key);

            ResultSet rs = st.executeQuery();
            clearTable();
            for (int i = 0; i < 10; i++) {
                if (rs.next()) {
                    id = rs.getInt(1);
                    fname = rs.getString(2);
                    lname = rs.getString(3);
                    age = rs.getInt(4);
                    gender = rs.getString(5);
                    address = rs.getString(6);
                    email = rs.getString(7);
                    phone = rs.getString(8);
                    date = rs.getString(9);

                    table1.setValueAt(id, i, 0);
                    table1.setValueAt(fname, i, 1);
                    table1.setValueAt(lname, i, 2);
                    table1.setValueAt(age, i, 3);
                    table1.setValueAt(gender, i, 4);
                    table1.setValueAt(address, i, 5);
                    table1.setValueAt(email, i, 6);
                    table1.setValueAt(phone, i, 7);
                    table1.setValueAt(date, i, 8);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void vsexItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vsexItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_vsexItemStateChanged

    private void btnaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseClicked
//        if (vname1.getText().isEmpty()||vname2.getText().isEmpty()) {
//            
//            JOptionPane.showMessageDialog(this, "fill name on field.", "error.", JOptionPane.ERROR_MESSAGE);
//      
//        }
//        
//        else if (vage.getText().isEmpty()) {
//             JOptionPane.showMessageDialog(this, "Enter age.", "error.", JOptionPane.ERROR_MESSAGE);
//      
//             
//        }
//        else if (vadd.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Enter address", "error.", JOptionPane.ERROR_MESSAGE);
//      
//             
//        }
//       else if (vemail.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Enter Email.", "error.", JOptionPane.ERROR_MESSAGE);
//      
//             
//        }
//       else if (vphone.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Enter phone number.", "error.", JOptionPane.ERROR_MESSAGE);
//      
//             
//        }
//        else{
//        java.util.Date date=new java.util.Date();
//        tasum.setText(tasum.getText() +"\n" + "\n" +"NAME : "+ vname1.getText() + " " + vname2.getText() + "\n" + "GENDER : " + vsex.getSelectedItem().toString()
//                    +"\n" + "AGE : " + vage.getText() +"\n" +"ADDRESS  : " + vadd.getText()+"\n"+ "EMAIL : " +vemail.getText() +"\n" + "PHONE# : " + vphone.getText()+"\n"+"DATE OF REG. : " +date.toString()+ "\n"+"\n" );
//             //int x=row;
//             for (int i = 0; i < 10; i++) {
//                Object k=table1.getValueAt(i, 0);
//                if (k == null) {
//                    int row=i;
//                    int x=row;
//                table1.setValueAt("0"+ ++x, row, 0);
//             table1.setValueAt(vname1.getText(), row, 1);
//             table1.setValueAt(vname2.getText(), row, 2);
//             table1.setValueAt(vage.getText(), row, 3);
//             table1.setValueAt(vsex.getSelectedItem().toString(), row, 4);
//             table1.setValueAt(vadd.getText(), row, 5);
//             table1.setValueAt(vemail.getText(), row, 6);
////             table1.setValueAt(vphone.getText(), row, 7);
//              table1.setValueAt(date, row, 8);
//             
//              
//          vname1.setText("");
//          vname2.setText("");
//          vage.setText("");
//          vadd.setText("");
//          vphone.setText("");
//          vemail.setText("");
//          vdate.setText("");
//          break;
//            }

//             }
//        }

    }//GEN-LAST:event_btnaddMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

        if (vname1.getText().isEmpty() || vname2.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "fill name on field.", "error.", JOptionPane.ERROR_MESSAGE);

        } else if (vage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter age.", "error.", JOptionPane.ERROR_MESSAGE);

        } else if (vadd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter address", "error.", JOptionPane.ERROR_MESSAGE);

        } else if (vemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Email.", "error.", JOptionPane.ERROR_MESSAGE);

        } else if (vphone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter phone number.", "error.", JOptionPane.ERROR_MESSAGE);

        } else if (vdate.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Reg. Date.", "error.", JOptionPane.ERROR_MESSAGE);

        } else if (tfid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter stuff member ID", "error.", JOptionPane.ERROR_MESSAGE);

        } else {
            int id = Integer.parseInt(tfid.getText());
            String fname = vname1.getText();
            String lname = vname2.getText();
            int age = Integer.parseInt(vage.getText());
            String gender = vsex.getSelectedItem().toString();
            String address = vadd.getText();
            String email = vemail.getText();
            String phone = vphone.getText();
            String date = vdate.getText();

            stuffTable(id, fname, lname, age, gender, address, email, phone, date);

        }


    }//GEN-LAST:event_btnaddActionPerformed

    private void pbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbuttonMouseClicked
        if (stuff_sum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Empty file.");
        } else {
            try {
                java.util.Date date = new java.util.Date();
                stuff_sum.setText(stuff_sum.getText() + "--------------------------------------------------------------------------------------------------------\n");
                stuff_sum.setText(stuff_sum.getText() + "Generated on : " + date.toString());
                stuff_sum.print();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_pbuttonMouseClicked

    private void pbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pbuttonActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int key = table1.getSelectedRow();
        String id = table1.getValueAt(key, 0).toString();
        String name = table1.getValueAt(key, 1).toString() + " " + table1.getValueAt(key, 1).toString();
        String age = table1.getValueAt(key, 3).toString();
        String gender = table1.getValueAt(key, 4).toString();
        String add = table1.getValueAt(key, 5).toString();
        String email = table1.getValueAt(key, 6).toString();
        String phone = table1.getValueAt(key, 7).toString();
        String date = table1.getValueAt(key, 8).toString();
//        stuff_sum.setBackground(Color.LIGHT_GRAY);
        stuff_sum.setText("*********************************MMM**********************************\n"
                + "**************************STUFF'S INFORMATION***********************\n\n"
                + "NAME  ......................................: " + name + "\n"
                + "ID ..............................................: " + id + " \n"
                + "AGE ...........................................: " + age + " \n"
                + "GENDER ...................................:" + gender + "\n"
                + "ADDERESS ...............................: " + add + "\n"
                + "E-MAIL .....................................: " + email + "\n"
                + "PHONE ......................................: " + phone + "\n"
                + "DATE .........................................:" + date + "\n"
                + "\n"
                + "*********************************************************************\n"
                + "\n"
                + "");
    }//GEN-LAST:event_table1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        stuff_sum.setText("");
        vname1.setText("");
        vname2.setText("");
        vage.setText("");
        vadd.setText("");
        vphone.setText("");
        vemail.setText("");
        vdate.setText("");
        int x = table1.getSelectedRow();
        if (table1.isRowSelected(x)) {
            table1.removeRowSelectionInterval(x, 0);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyPressed

    private void tfsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfsearchActionPerformed

    private void tfsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfsearchMouseClicked
        // TODO add your handling code here:
        tfsearch.setText("");
    }//GEN-LAST:event_tfsearchMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
//
//        int key = table1.getSelectedRow();
//        if (table1.isRowSelected(key)) {
//            if (vname1.getText().equals("")) {
//                vname1.setText(table1.getValueAt(key, 1).toString());
//                vname2.setText(table1.getValueAt(key, 2).toString());
//                vage.setText(table1.getValueAt(key, 3).toString());
//                vadd.setText(table1.getValueAt(key, 5).toString());
//                vphone.setText(table1.getValueAt(key, 7).toString());
//                vemail.setText(table1.getValueAt(key, 6).toString());
//                vdate.setText(table1.getValueAt(key, 8).toString());
//            } else {
//
//                table1.setValueAt(vname1.getText(), key, 1);
//                table1.setValueAt(vname2.getText(), key, 2);
//                table1.setValueAt(vage.getText(), key, 3);
//                table1.setValueAt(vsex.getSelectedItem().toString(), key, 4);
//                table1.setValueAt(vadd.getText(), key, 5);
//                table1.setValueAt(vemail.getText(), key, 6);
//                table1.setValueAt(vphone.getText(), key, 7);
//                table1.setValueAt(vdate.getText(), key, 8);
//
//                tasum.setText("                                             :::::::::::::MMS:::::::::::::\n"
////                        + "_____________________________________________________________________\n"
//                        + "STUFF MEMBER IMFORMATION DETAILS \n"
//                        + "--------------------------------------------------------------------------------------------------------");
//                vname1.setText("");
//                vname2.setText("");
//                vage.setText("");
//                vadd.setText("");
//                vphone.setText("");
//                vemail.setText("");
//                vdate.setText("");

//        int key = table1.getSelectedRow();
//        if (table1.isRowSelected(key)) {
//            if (vname1.getText().equals("")) {
//                vname1.setText(table1.getValueAt(key, 1).toString());
//                vname2.setText(table1.getValueAt(key, 2).toString());
//                vage.setText(table1.getValueAt(key, 3).toString());
//                vadd.setText(table1.getValueAt(key, 5).toString());
//                vphone.setText(table1.getValueAt(key, 7).toString());
//                vemail.setText(table1.getValueAt(key, 6).toString());
//                vdate.setText(table1.getValueAt(key, 8).toString());
//            } else {
//
//                table1.setValueAt(vname1.getText(), key, 1);
//                table1.setValueAt(vname2.getText(), key, 2);
//                table1.setValueAt(vage.getText(), key, 3);
//                table1.setValueAt(vsex.getSelectedItem().toString(), key, 4);
//                table1.setValueAt(vadd.getText(), key, 5);
//                table1.setValueAt(vemail.getText(), key, 6);
//                table1.setValueAt(vphone.getText(), key, 7);
//                table1.setValueAt(vdate.getText(), key, 8);
//
//                tasum.setText("                                             :::::::::::::MMS:::::::::::::\n"
////              
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "select row to update.", "update", JOptionPane.OK_OPTION);
//        }
//

    }//GEN-LAST:event_btnupdateMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int key = table1.getSelectedRow();

        if (table1.isRowSelected(key)) {

            sid.setText(table1.getValueAt(key, 0).toString());
            tfname1.setText(table1.getValueAt(key, 1).toString());
            tfname2.setText(table1.getValueAt(key, 2).toString());
            tfage.setText(table1.getValueAt(key, 3).toString());
            //tfgender.setText(table1.getValueAt(key, 1).toString());
            tfadd.setText(table1.getValueAt(key, 5).toString());
            tfemail.setText(table1.getValueAt(key, 6).toString());
            tfphone.setText(table1.getValueAt(key, 7).toString());
            tfdate.setText(table1.getValueAt(key, 8).toString());

            updialog.setLocationRelativeTo(null);
            updialog.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "select row to be updated first.", "select!!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void vdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vdateActionPerformed

    private void vname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vname1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_vname1KeyPressed

    private void btnupdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateMouseEntered

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        int y = table1.getSelectedRow();
        if (table1.isRowSelected(y)) {
            int t = JOptionPane.showConfirmDialog(this, "you sure?", "confirm.", JOptionPane.YES_NO_OPTION);
            if (t == JOptionPane.YES_OPTION) {
                table1.setValueAt(null, y, 0);
                table1.setValueAt(null, y, 1);
                table1.setValueAt(null, y, 2);
                table1.setValueAt(null, y, 3);
                table1.setValueAt(null, y, 4);
                table1.setValueAt(null, y, 5);
                table1.setValueAt(null, y, 6);
                table1.setValueAt(null, y, 7);
                table1.setValueAt(null, y, 8);
            } else {
                table1.removeRowSelectionInterval(y, 0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "select row to delete.", "update", JOptionPane.OK_OPTION);

        }

    }//GEN-LAST:event_btndeleteMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String y = JOptionPane.showInputDialog(this, "ID of Stuff member to be deleted.", "Enter ID", JOptionPane.INFORMATION_MESSAGE);
        if (!y.isEmpty()) {
            deleteStuff(y);
        } else {
            System.out.println("delete canceled");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tfhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfhomeMouseClicked
        Dashboard b = new Dashboard();
        dispose();
        b.setTitle("HOME");
        b.setLocationRelativeTo(null);
        b.setVisible(true);

    }//GEN-LAST:event_tfhomeMouseClicked

    private void vname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vname2ActionPerformed

    private void tfaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaddActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        int key = table1.getSelectedRow();
        String preId = table1.getValueAt(key, 0).toString();
        String id = sid.getText();
        String fname = tfname1.getText();
        String lname = tfname2.getText();
        int age = Integer.parseInt(tfage.getText());
        String gender = (String) cbgender.getSelectedItem();
        String add = tfadd.getText();
        String email = tfemail.getText();
        String phone = tfphone.getText();
        String date = tfdate.getText();

        updateStuff(preId, id, fname, lname, age, gender, add, email, phone, date);
        clearTable();
        displayTable();

    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        updialog.setVisible(false);
    }//GEN-LAST:event_btncloseActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        displayTable();
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stuff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbsearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pbutton;
    private javax.swing.JTextField sid;
    private javax.swing.JTextArea stuff_sum;
    private javax.swing.JTable table1;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfage;
    private javax.swing.JTextField tfdate;
    private javax.swing.JTextField tfemail;
    private javax.swing.JLabel tfhome;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfname1;
    private javax.swing.JTextField tfname2;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfsearch;
    private javax.swing.JDialog updialog;
    private javax.swing.JTextField vadd;
    private javax.swing.JTextField vage;
    private javax.swing.JTextField vdate;
    private javax.swing.JTextField vemail;
    private javax.swing.JTextField vname1;
    private javax.swing.JTextField vname2;
    private javax.swing.JTextField vphone;
    private javax.swing.JComboBox<String> vsex;
    // End of variables declaration//GEN-END:variables

    private void stuffTable(int id, String fname, String lname, int age, String gender, String address, String email, String phone, String date) {
        try {
            Connection connect = (Connection) DBconnection.connectDB();
            PreparedStatement st = (PreparedStatement) connect.prepareStatement("INSERT INTO stuffs VALUES (?,?,?,?,?,?,?,?,?)");
            st.setInt(1, id);
            st.setString(2, fname);
            st.setString(3, lname);
            st.setInt(4, age);
            st.setString(5, gender);
            st.setString(6, address);
            st.setString(7, email);
            st.setString(8, phone);
            st.setString(9, date);
            int x = st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Stuff added successfully");
            tfid.setText("");
            vname1.setText("");
            vname2.setText("");
            vage.setText("");
            vadd.setText("");
            vphone.setText("");
            vemail.setText("");
            vdate.setText("");
            connect.close();
            displayTable();

        } catch (SQLException ex) {
            Logger.getLogger(stuff.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void displayTable() {
        int id = 0;
        String fname = "";
        String lname = "";
        int age = 0;
        String gender = "";
        String address = "";
        String email = "";
        String phone = "";
        String date = "";
        try {
            Connection conn = (Connection) DBconnection.connectDB();
            PreparedStatement add = (PreparedStatement) conn.prepareStatement("SELECT * FROM stuffs");
            ResultSet rs = add.executeQuery();
//            table1.setModel(DbUtils.resultSetToTableModel(rs));
            int no_row = table1.getRowCount();
            for (int i = 0; i < no_row; i++) {
                if (rs.next()) {
                    id = rs.getInt(1);
                    fname = rs.getString(2);
                    lname = rs.getString(3);
                    age = rs.getInt(4);
                    gender = rs.getString(5);
                    address = rs.getString(6);
                    email = rs.getString(7);
                    phone = rs.getString(8);
                    date = rs.getString(9);

                    table1.setValueAt(id, i, 0);
                    table1.setValueAt(fname, i, 1);
                    table1.setValueAt(lname, i, 2);
                    table1.setValueAt(age, i, 3);
                    table1.setValueAt(gender, i, 4);
                    table1.setValueAt(address, i, 5);
                    table1.setValueAt(email, i, 6);
                    table1.setValueAt(phone, i, 7);
                    table1.setValueAt(date, i, 8);
                }
            }
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearTable() {
        int no = table1.getRowCount();
        for (int i = 0; i < no; i++) {
            table1.setValueAt(null, i, 0);
            table1.setValueAt(null, i, 1);
            table1.setValueAt(null, i, 2);
            table1.setValueAt(null, i, 3);
            table1.setValueAt(null, i, 4);
            table1.setValueAt(null, i, 5);
            table1.setValueAt(null, i, 6);
            table1.setValueAt(null, i, 7);
            table1.setValueAt(null, i, 8);
        }
    }

    private void deleteStuff(String y) {
        try {
            Connection conn = (Connection) DBconnection.connectDB();
            PreparedStatement delete = (PreparedStatement) conn.prepareStatement("DELETE FROM stuffs WHERE id=?");
            delete.setInt(1, Integer.parseInt(y));
            int x = delete.executeUpdate();
            conn.close();
            clearTable();
            displayTable();
        } catch (SQLException ex) {
            Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateStuff(String preId, String id, String fname, String lname, int age, String gender, String add, String email, String phone, String date) {
        try {
            Connection conn = (Connection) DBconnection.connectDB();
            PreparedStatement update = (PreparedStatement) conn.prepareStatement("UPDATE stuffs SET id=?,fname=?,lname=?,age=?,gender=?,address=?,email=?,phone=?,date=? WHERE id=? ");
            update.setString(1, id);
            update.setString(2, fname);
            update.setString(3, lname);
            update.setInt(4, age);
            update.setString(5, gender);
            update.setString(6, add);
            update.setString(7, email);
            update.setString(8, phone);
            update.setString(9, date);
            update.setString(10, preId);
            int y = update.executeUpdate();
            JOptionPane.showMessageDialog(this, "Stuff updated ");
            updialog.setVisible(false);
            conn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Visitors.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
