/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import src.login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public UserRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        lname2 = new javax.swing.JTextField();
        fname2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        notify = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tffname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfuserid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        tfadd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbgender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tfphone = new javax.swing.JTextField();
        btnregister = new javax.swing.JButton();
        tflname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfpassword = new javax.swing.JTextField();
        btnshowlogin = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tfanswer = new javax.swing.JTextField();
        cbqlist = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfage = new javax.swing.JTextField();
        backimage = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Lastname");

        lname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        fname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Firstname");

        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setForeground(new java.awt.Color(44, 4, 105));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("User Register Form");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LISTTTTT.jpg"))); // NOI18N

        notify.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        notify.setForeground(new java.awt.Color(255, 0, 0));
        notify.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notify, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(notify)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lastname");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(9, 61, 60, 20);

        tffname.setBackground(new java.awt.Color(204, 204, 255));
        tffname.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tffname.setToolTipText("acts as username");
        tffname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tffname);
        tffname.setBounds(9, 35, 160, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Firstname");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(9, 9, 60, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(225, 113, 60, 20);

        tfuserid.setBackground(new java.awt.Color(204, 204, 255));
        tfuserid.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfuserid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tfuserid);
        tfuserid.setBounds(10, 190, 160, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Enter user ID:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 170, 120, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-mail address");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(403, 9, 120, 20);

        tfemail.setBackground(new java.awt.Color(204, 204, 255));
        tfemail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tfemail);
        tfemail.setBounds(403, 35, 160, 20);

        tfadd.setBackground(new java.awt.Color(204, 204, 255));
        tfadd.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tfadd);
        tfadd.setBounds(225, 35, 160, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(225, 9, 60, 20);

        cbgender.setBackground(new java.awt.Color(0, 0, 51));
        cbgender.setForeground(new java.awt.Color(255, 255, 255));
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cbgender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbgenderItemStateChanged(evt);
            }
        });
        jPanel3.add(cbgender);
        cbgender.setBounds(225, 139, 76, 26);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone #");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(225, 61, 100, 20);

        tfphone.setBackground(new java.awt.Color(204, 204, 255));
        tfphone.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfphone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tfphone);
        tfphone.setBounds(225, 87, 160, 20);

        btnregister.setBackground(new java.awt.Color(255, 102, 0));
        btnregister.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnregister.setText("Register");
        btnregister.setActionCommand("");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel3.add(btnregister);
        btnregister.setBounds(70, 220, 80, 27);

        tflname.setBackground(new java.awt.Color(204, 204, 255));
        tflname.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tflname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tflname);
        tflname.setBounds(9, 87, 160, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(403, 116, 69, 15);

        tfpassword.setBackground(new java.awt.Color(204, 204, 255));
        tfpassword.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfpassword.setToolTipText("acts as password");
        tfpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tfpassword);
        tfpassword.setBounds(403, 139, 160, 20);

        btnshowlogin.setBackground(new java.awt.Color(255, 102, 0));
        btnshowlogin.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnshowlogin.setText("Back to login");
        btnshowlogin.setActionCommand("");
        btnshowlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowloginActionPerformed(evt);
            }
        });
        jPanel3.add(btnshowlogin);
        btnshowlogin.setBounds(170, 220, 120, 27);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Security question:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(270, 170, 110, 20);

        tfanswer.setBackground(new java.awt.Color(204, 204, 255));
        tfanswer.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfanswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tfanswer);
        tfanswer.setBounds(380, 200, 90, 20);

        cbqlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your birth place?", "What is your favourite color?", "What is your favourite food?" }));
        jPanel3.add(cbqlist);
        cbqlist.setBounds(380, 170, 180, 26);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Username");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(403, 61, 90, 20);

        tfusername.setBackground(new java.awt.Color(204, 204, 255));
        tfusername.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tfusername);
        tfusername.setBounds(403, 87, 160, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Age");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(9, 113, 60, 20);

        tfage.setBackground(new java.awt.Color(204, 204, 255));
        tfage.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(tfage);
        tfage.setBounds(9, 142, 160, 20);

        backimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regimg.jpg"))); // NOI18N
        jPanel3.add(backimage);
        backimage.setBounds(0, -50, 570, 310);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 570, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        if (tfuserid.getText().isEmpty() || tffname.getText().isEmpty() || tflname.getText().isEmpty() || tfuserid.getText().isEmpty() || tfemail.getText().isEmpty() || tfadd.getText().isEmpty() || tfphone.getText().isEmpty() || tfanswer.getText().isEmpty() || tfpassword.getText().isEmpty() || tfanswer.getText().isEmpty()) {
            notify.setText("***Fill the form properly !***");
        } else {
            notify.setText("");
            int user_id = Integer.parseInt(tfuserid.getText());
            String fname = tffname.getText();
            String lname = tflname.getText();
            int age = Integer.parseInt(tfage.getText());
            String gender = cbgender.getSelectedItem().toString();
            String email = tfemail.getText();
            String phone = tfphone.getText();
            String address = tfadd.getText();
            String username = tfusername.getText();
            String password = tfpassword.getText();
            String answer = tfanswer.getText();
            int index = cbqlist.getSelectedIndex();

            insertBackup(index, answer, user_id);

            userRegister(user_id, fname, lname, age, gender, address, email, phone, username, password);

        }
    }//GEN-LAST:event_btnregisterActionPerformed

    private void cbgenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbgenderItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgenderItemStateChanged

    private void btnshowloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowloginActionPerformed
        login t = new login();
        dispose();
        t.setTitle("login");
        t.setLocationRelativeTo(null);
        t.setVisible(true);
    }//GEN-LAST:event_btnshowloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UserRegister().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backimage;
    public javax.swing.JButton btnregister;
    private javax.swing.JButton btnshowlogin;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbqlist;
    private javax.swing.JTextField fname2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField lname2;
    private javax.swing.JLabel notify;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfage;
    private javax.swing.JTextField tfanswer;
    private javax.swing.JTextField tfemail;
    public javax.swing.JTextField tffname;
    private javax.swing.JTextField tflname;
    public javax.swing.JTextField tfpassword;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfuserid;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables

    private void userRegister(int user_id, String fname, String lname, int age, String gender, String address, String email, String phone, String username, String password) {
        Connection connect = DBconnection.connectDB();//now its connected
        try {
            PreparedStatement statement = (PreparedStatement) connect.prepareStatement("INSERT INTO users VALUES (?,?,?,?,?,?,?,?,?,?)");
            statement.setInt(1, user_id);
            statement.setString(2, fname);
            statement.setString(3, lname);
            statement.setString(4, gender);
            statement.setInt(5, age);
            statement.setString(6, address);
            statement.setString(8, email);
            statement.setString(7, phone);
            statement.setString(9, username);
            statement.setString(10, password);
            int result = statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "User data is inserted.", "success!!.", JOptionPane.INFORMATION_MESSAGE);
            connect.close();
            tffname.setText("");
            tflname.setText("");
            tfadd.setText("");
            tfemail.setText("");
            tfphone.setText("");
            tfpassword.setText("");
            tfanswer.setText("");
            tfuserid.setText("");
            tfage.setText("");
            tfusername.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void insertBackup(int index, String answer, int user_id) {
        try {
            Connection connect=DBconnection.connectDB();
            PreparedStatement st=(PreparedStatement)
                    connect.prepareStatement("INSERT INTO backup VALUES (?,?,?,?)");
            
            st.setInt(1, 0);
            st.setString(2, String.valueOf(index));
            st.setString(3, answer);
            st.setString(4, String.valueOf(user_id));
            int x=st.executeUpdate();
            
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(UserRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
